### ISSUE TITLE
Chrome fails to remove '.parsley_synthetic_submit_button' before submit

### ISSUE THREAD

**Issue by swiggins** [guillaumepotier/Parsley.js#1047]
Using the following basic html
```
<form action="test.html" data-parsley-validate>
            <input type="text" required />
            <input type="submit" name="savebutton" value="savevalue"/>
</form>
```
On submission Chrome (v48.0.2564.82m) will try to GET the following, note the extra savebutton form field.
test.html?savebutton=savevalue&savebutton=savevalue

Firefox, IE and Edge will return
test.html?savebutton=savevalue

It looks to me like the .parsley_synthetic_submit_button is not being removed correctly before the form is submitted. Parsley v2.2.0

**Comment by marcandre** [comment]
I'm not sure this can really cause issues, but it doesn't look good.

Parsley interrupts the submit event and re-submits it after validation is finished.
Turns out browsers behave differently when we call `submit` from within a `submit` event.
Mmm, it's not even clear which browser is right.
I tweaked it in `master` by sidestepping the issue completely and not interrupting the submit event if validation is already resolved and successful.
Thanks for bringing this up.

**Comment by jedrzejchalubek** [comment]
I've updated parsley to 310b4cbdc7, but problem still presist.

After clicking submit:
`<input type="submit" name="submit" id="submit" class="button button-primary" value="Submit">`

Hidden input shows up and block submit:
`<input class="parsley_synthetic_submit_button" type="hidden" name="submit" value="Submit">`

**Comment by marcandre** [comment]
Thanks for testing `master`.
Are you sure you are testing that version though? I renamed the class to use `-` instead of `_`... so if you see `parsley_synthetic_submit_button`, then you are using the previous version!
I'm also not sure what you mean by blocking the submit. Finally, if you are not using async validations, you won't see the synthetic input anymore.

**Comment by jedrzejchalubek** [comment]
I've been pulling `dist` version which is not compiled yet. It works now, thanks.
